### ISSUE TITLE
How can I get to the code for `ATAC-seq` ?

### ISSUE THREAD

**Issue by jiangpuxuan** [angleYuan/gata5_SC#1]
Hi,
I am from Institute of Genetics and Development Biology, Chinses Acadamy of Science, and I am very appreciated at your work.
So. how can I find the code for `ATAC-seq` of gata5GFP+/- cells in WT and Gata5/6 deficient zebrafish embryos ?
Thank you very much.

**Comment by angleYuan** [comment]
Thank you for your interest in our work! Sorry for the delay but ATAC-seq code has been uploaded by now. If you are interested in some specific analysis or find anything missing, please let us know.

Best,
Xuefei
